/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    Auth: {
        region: 'ap-southeast-1',
        userPoolId: 'ap-southeast-1_EWYysw4Rf',
        userPoolWebClientId: '6i8k5q15esdhaiikd9jbd163he',
    },

    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://rumxbhum3redjj7jsb3jwugd6i.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-xrpj5wcv6bckzd5ssflpdg2hmq"
};


export default awsmobile;
