version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HttpAPIStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kqaimkyznuj1"
s3_prefix = "HttpAPIStack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "UserPoolId=\"\" Audience=\"\""
